name: rses-onco
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - networkx
  - requests
  - pyyaml
  - openpyxl
  - pillow
  - pytest
  - mafft
  - fasttree
  - pymol-open-source
  - pip
  - pip:
      - -e .
